export const FETCH_WORDPRESS_CONTENT_START = "FETCH WORDPRESS CONTENT START";
export const FETCH_WORDPRESS_CONTENT_SUCCESS =
  "FETCH WORDPRESS CONTENT SUCCESS";
export const FETCH_WORDPRESS_CONTENT_FAIL = "FETCH WORDPRESS CONTENT FAIL";
