export const TOGGLE_FORM = "TOGGLE_FORM";
export const TOGGLE_PANEL = "TOGGLE_PANEL";

export const SET_FORM_VALUE = "SET_FORM_VALUE";
export const SET_HIDDEN_FORM_VALUE = "SET_HIDDEN_FORM_VALUE";

export const SUBMIT_FORM = "SUBMIT_FORM";
export const SUBMIT_FORM_SUCCESS = "SUBMIT_FORM_SUCCESS";
export const SUBMIT_FORM_FAIL = "SUBMIT_FORM_FAIL";

export const ACTIVE_AB_TESTING = "ACTIVE_AB_TESTING";
export const SET_VARIANT = "SET_VARIANT";

export const INIT_STATE = "INIT_STATE";
export const INIT_FORM_STATE = "INIT_FORM_STATE";


export const SWITCH_SELECTED_IMAGE = "SWITCH_SELECTED_IMAGE";
export const SWITCH_SELECTED_IMAGE_SUCCESS = "SWITCH_SELECTED_IMAGE_SUCCESS";
export const SWITCH_SELECTED_IMAGE_FAIL = "SWITCH_SELECTED_IMAGE_FAIL";