export const FETCH_WORDPRESS_CONTENT_START = "FETCH WORDPRESS CONTENT START";
export const FETCH_WORDPRESS_CONTENT_SUCCESS =
  "FETCH WORDPRESS CONTENT SUCCESS";
export const FETCH_WORDPRESS_CONTENT_FAIL = "FETCH WORDPRESS CONTENT FAIL";

export const SWITCH_SELECTED_IMAGE = "SWITCH_SELECTED_IMAGE";
export const SWITCH_SELECTED_IMAGE_SUCCESS = "SWITCH_SELECTED_IMAGE_SUCCESS";
export const SWITCH_SELECTED_IMAGE_FAIL = "SWITCH_SELECTED_IMAGE_FAIL";
